### ISSUE TITLE
Not appearing in devices

### ISSUE THREAD

**Issue by runderkm** [SergeRegoor/com.visionsecurity#1]
Great that you created an app for this. I added it succesfully and I can see it in Devices. The problem is that I cannot choose the device when creating a flow. I cannot find it in the list of triggers.

**Comment by SergeRegoor** [comment]
Sorry for the late reply. I'm not sure the siren sends a command when the siren is activated. I'm using it currently only to switch it on, or off, using the most right column in the flow editor.

**Comment by runderkm** [comment]
What I meant is that I does not show up at all when I want to make a flow, see the attached screenshots.
I am currently using V.1.1.0 of the app and I am on Homey Firmware Versie: 1.0.1. I have tried removing and adding the device again, but this did not help.

![flows](https://cloud.githubusercontent.com/assets/23473904/20624553/d335f080-b30d-11e6-8a2a-59fc57437f27.png)
![zones](https://cloud.githubusercontent.com/assets/23473904/20624565/e2c78734-b30d-11e6-84e5-7192586bbb1d.png)

**Comment by SergeRegoor** [comment]
I understand now! And can also reproduce. No idea why this happens though, I'll have to check with Athom.

**Comment by SergeRegoor** [comment]
Found the issue, and fixed it. New version of the app is awaiting approval in the App Store.
Please note that the siren needs to be re-paired with Homey.

**Comment by runderkm** [comment]
The problem is indeed fixed. Thanks a lot!
